Add zProperty for Windows services class grouping
zenoss/ZenPacks.zenoss.Microsoft.Windows pull request #1201
Opened 2022-04-07 14:13 UTC by odubrovyk

Fixes ZPS-8115.

Added zWinServicesGroupedByClass property for Windows Service
classes to model services with generic Windows Service class.

2022-04-07 14:33 UTC, StevePC requested changes
Need some documentation explaining what the contents of the zProp should be and exactly what it does.

2022-04-07 20:10 UTC, StevePC requested changes

2022-04-07 20:10 UTC, StevePC commented on docs/body.md
> +        This property should be used when a target Windows device has a lot of Windows Services with rotating name extension - "<service_name>_0123456789bcdef". Each of these services creates separat
probably don't need to mention ZODB locking, but should mention that the regex is used in search() not match(), so not anchored to the start of the name, and that the regex supplied has no bearing on what is removed from the service name to arrive at the service class name, it simply removes the last underscore and everything following it.

2022-04-07 20:10 UTC, StevePC commented on ZenPacks/zenoss/Microsoft/Windows/tests/testServicesRegex.py
> +    def test_model_service_grouped_multiple(self):
might want to include tests for grouping services with multiple underscores in the name

2022-04-07 21:43 UTC, jeff-powell requested changes
Made some suggestions, but looks great.  StevePC also dropped in a comment too (regarding the documentation.)

2022-04-07 21:43 UTC, jeff-powell commented on ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Services.py
> +        return service_class_name, service_class_caption
I  don't think you need the 'else' section.  Just set the default to return at the end.

2022-04-08 16:16 UTC, StevePC approved these changes

2022-04-12 07:42 UTC, merged